apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: browserify-love-demo-API
  annotations:
    github.com/project-slug: fabiodamasceno/browserify-love-demo
spec:
  type: API
  lifecycle: production
  owner: guests


kind: Component
metadata:
  name: browserify-love-demo-component
  annotations:
    github.com/project-slug: fabiodamasceno/browserify-love-demo
spec:
  type: API
  lifecycle: production
  owner: guests
